name: Symbol extraction validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Extract mod symbols
        run: |
          python .github/extract_mod_symbols.py mods -
